# Generated by Django 3.2.9 on 2021-11-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
